version: '3'
services:

  nginx:
    container_name: nginx
    image: nginx:alpine

    ports:
      - 8083:80

    volumes:
      - ./conf.d:/etc/nginx/conf.d

    networks:
      - custom

    depends_on:
      - web

  web:
    container_name: web
    build: .
    command: /bin/bash -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0"

    ports:
      - 8000:8000
    volumes:
      - .:/app/

    networks:
      - custom

    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    env_file:
      - .env
    networks:
      - custom

networks:
  custom:
#    driver: bridge

#version: '3'
#services:
#  web:
#    build: .
#    command: /bin/bash -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0"
#    ports:
#      - 8000:8000
#    volumes:
#      - .:/app/
#
#    depends_on:
#      - db
#
#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#      - 5433:5432
#    env_file:
#      - .env